spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pagos_db}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:user123}

loader:
  path: ${LOADER_PATH:C:/apps/ms-pagos/input}

logging:
  level:
    root: INFO
    com.rassini.pagos: DEBUG
    org.springframework: INFO
    org.hibernate: ERROR