spring.application.name=pagos-loader

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/pagos_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:user123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Loader
loader.path=/opt/pagos/input

# Server
server.servlet.context-path=/portal
server.port=8080

#  Logs (limpios)
logging.level.root=INFO
logging.level.com.rassini.pagos=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=ERROR

#  Errores visibles en Postman
server.error.include-message=always
server.error.include-binding-errors=always

# ACTUATOR
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Tag útil para Prometheus
management.metrics.tags.application=pagos-loader

management.endpoint.health.show-components=always

server.address=0.0.0.0