-- ============================================================
-- INSERT INTO equivalences_deal_type
-- Fuente: Catalogs Graphite FINAL 1 (1).xlsx
-- Hoja: Purchase DEAL Type (sección Graphite, filas 72+)
-- 6 BUs procesadas: 0111, 0111(QAD), 02, 1000, 1850, 0301
-- ============================================================

-- BU 0111 (Graphite Supplier View): code=Col B, des_code=Col C, equivalences=Col O (44 registros)
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'MATERIA PRIMA', 'RAW MATERIAL', 'SUPPLIERM');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'CHATARRA', 'SCRAP METAL', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'MATERIAL INDIRECTO', 'INDIRECT MATERIAL', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'HERRAMENTALES', 'TOOLS', 'SUPPLIEM');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'HERRAMIENTA DE CORTE', 'CUTTING TOOL', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'COMPONENTES', 'COMPONENTS', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'REFACCIONES', 'SPARE PARTS', 'SUPPLIEVM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ACTIVO FIJO', 'FIXED ASSETS', 'CAPEX');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'FLETES', 'FLETS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SERV TERCERIZADOS', 'OUTSOURCED SERVICES', 'SERVICIOS');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'REPSE', 'REPSE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SERV COMUNICACION', 'COMMUNICATION SERVICE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SERVICIOS DE COMEDOR', 'DINING SERVICES', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SERVICIO DE TELEFONIA', 'TELEPHONE SERVICE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SERVICIO DE VIGILANCIA', 'SURVEILLANCE SERVICE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SERV EXTERNOS', 'EXTERNAL SERVICES', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SERVICIOS', 'SERVICES', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'HONORARIOS', 'FEES', 'SUPPLIEV');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ASESORIAS', 'CONSULTANCIES', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SERVICIOS ADUANALES', 'CUSTOMS SERVICES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'MAQUILA', 'MAQUILA', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'IMPUESTOS Y DERECHOS', 'TAXES AND DUTIES', 'IMPUESTOS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'AGUA', 'WATER', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ARRENDAMIENTO EQUIPO', 'EQUIPMENT LEASING', 'SUPPLIEF');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ARRENDAMIENTO INMUEBLE', 'REAL ESTATE LEASING', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ARRENDAMIENTO', 'LEASING', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ENERGIA/ ENERGETICOS', 'ENERGY/ENERGY', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'INTERCOMPANIA', 'INTERCOMPANY', 'INTERTRANS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'NOMINA EMPLEADO', 'EMPLOYEE PAYROLL', 'NOMINA');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'NOMINA SINDICALIZADO', 'UNIONIZED PAYROLL', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'RESICO', 'RESICO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'SISTEMAS', 'SYSTEMS', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ABOGADOS', 'LAWYERS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'MANTENIMIENTO', 'MAINTENANCE', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'CALIDAD', 'QUALITY', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ECOLOGÍA', 'ECOLOGY', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'MATERIAL DE EMPAQUE', 'PACKAGING MATERIAL', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'CASTING', 'CASTING', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'DIVERSOS', 'MISCELLANEOUS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'EQUIPO DE MEDICION', 'MEASURING EQUIPMENT', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'FERRO ALEACIONES', 'FERRO ALLOYS', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'ADMO', 'ADMO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'GASTOS DE VIAJE', 'TRAVEL EXPENSES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'OTROS', 'OTHER', 'SUPPLIEV');

-- BU 0111 (QAD Corpo, celda E70): code=Col E, des_code=Col D, equivalences=Col O (24 registros)
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B001', 'MATERIA PRIMA', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B021', 'MATERIALES INDIRECTOS', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B002', 'HERRAMIENTAS/HERRAMENTAL', 'SUPPLIEM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B003', 'REFACCIONES', 'SUPPLIEVM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B005', 'ACTVO FIJO', 'CAPEX');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B009', 'FLETES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B006', 'SERV TERCERIZADOS', 'SERVICIOS');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B015', 'SERV COMUNICACION', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B007', 'SERV EXTERNOS', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B008', 'HONORARIOS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B010', 'SERV ADUANALES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B011', 'MAQUILA', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B012', 'IMPUESTOS Y DERECHOS', 'IMPUESTOS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B014', 'AGUA', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B016', 'ARRENDAMIENTO EQUIPO', 'SUPPLIEF');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B017', 'ARRENDAMIENTO INMUEBLE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B024', 'ARRENDAMIENTO', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B013', 'ENERGIA', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B018', 'INTERCOMPANIA', 'INTERTRANS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B019', 'NOMINA EMPLEADO', 'NOMINA');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B020', 'NOMINA SINDICALIZADO', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B023', 'RESICO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B004', 'INTANGIBLES', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0111', 'B022', 'OTROS ARTICULOS', 'SUPPLIEV');

-- BU 09 (QAD Suspensiones, celda G70): code=Col G, des_code=Col F, equivalences=Col O (14 registros)
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'MAPI', 'MATERIA PRIMA', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'COMP', 'COMPONENTES', 'SUPPLIEM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'ACFI', 'ACTIVOS FIJOS', 'CAPEX');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'GVAR', 'GASTOS VARIABLES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'IMPT', 'IMPUESTOS', 'IMPUESTOS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'GFIO', 'GASTOS FIJOS', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'INTE', 'INTERCOMPANIA', 'INTERTRANS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'NOMI', 'NOMINA', 'NOMINA');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'OTRO', 'OTRO TIPO DE GASTO', 'SUPPLIEV');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'CBIB', 'COMISIONES E INTERESES', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'CORI', 'COMISIONES RASSINI INTERNACIONAL', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'CORP', 'PAGOS CORPORATIVO', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'DEVO', 'DEVOLUCI\U00D3N A CORPO Y CHEQUE DE PROVEEDOR', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('09', 'STAF', 'STAFF MARASA', NULL);

-- BU 1000 (QAD Frenos, celda I70): code=Col I, des_code=Col H, equivalences=Col O (25 registros)
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'MP', 'MATERIA PRIMA', 'SUPPLIERM');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'CH', 'CHATARRA', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'MI', 'MATERIAL INDIRECTO', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'HT', 'HERRAMENTALES', 'SUPPLIEM');
I--NSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'HC', 'HERRAMIENTA DE CORTE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'CM', 'COMPONENTES', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'RE', 'REFACCIONES', 'SUPPLIEVM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'AF', 'ACTIVO FIJO', 'CAPEX');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'FL', 'FLETES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'SE', 'SERVICIOS', 'SERVICIOS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'TR', 'TRAFICO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'SN', 'SN', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'EN', 'ENERGÉTICOS', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'SN', 'SN', 'INTERTRANS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'SI', 'SISTEMAS', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'AB', 'ABOGADOS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'MT', 'MANTENIMIENTO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'CA', 'CALIDAD', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'EC', 'ECOLOGÍA', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'ME', 'MATERIAL DE EMPAQUE', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'CT', 'CASTING', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'DI', 'DIVERSOS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'EM', 'EQUIPO DE MEDICION', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'FE', 'FERRO ALEACIONES', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1000', 'SN', 'SN', 'SUPPLIEV');

-- BU 1850 (QAD Brakes, celda K70): code=Col K, des_code=Col J, equivalences=Col O (25 registros)
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'MP', 'MATERIA PRIMA', 'SUPPLIERM');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'CH', 'CHATARRA', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'MI', 'MATERIAL INDIRECTO', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'HT', 'HERRAMENTALES', 'SUPPLIEM');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'HC', 'HERRAMIENTA DE CORTE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'CM', 'COMPONENTES', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'RE', 'REFACCIONES', 'SUPPLIEVM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'AF', 'ACTIVO FIJO', 'CAPEX');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'FL', 'FLETES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'SE', 'SERVICIOS', 'SERVICIOS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'TR', 'TRAFICO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'SN', 'SN', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'EN', 'ENERGÉTICOS', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'SN', 'SN', 'INTERTRANS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'SI', 'SISTEMAS', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'AB', 'ABOGADOS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'MT', 'MANTENIMIENTO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'CA', 'CALIDAD', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'EC', 'ECOLOGÍA', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'ME', 'MATERIAL DE EMPAQUE', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'CT', 'CASTING', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'DI', 'DIVERSOS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'EM', 'EQUIPO DE MEDICION', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'FE', 'FERRO ALEACIONES', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('1850', 'SN', 'SN', 'SUPPLIEV');

-- BU 0301 (QAD Bypasa, celda M70): code=Col M, des_code=Col L, equivalences=Col O (53 registros)
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'MAPI', 'MATERIA PRIMA', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B021', 'MATERIALES INDIRECTOS', 'SUPPLIERM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'HTAS', 'HERRAMIENTAS Y MTTO HERRAMENTALES', 'SUPPLIEM');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'COMP', 'COMPONENTES', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B003', 'REFACCIONES', 'SUPPLIEVM');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'ACFI', 'ACTIVO FIJO', 'CAPEX');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'FLET', 'FLETES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B006', 'SERV TERCERIZADOS', 'SERVICIOS');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B025', 'REPSE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B015', 'SERV COMUNICACION', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'COME', 'SERVICIOS DE COMEDOR', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'TELE', 'SERVICIO DE TELEFONIA', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'VIGI', 'SERVICIO DE VIGILANCIA', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B007', 'SERV EXTERNOS', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C007', 'SERVICIOS', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'HONO', 'HONORARIOS Y ASESORIAS', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B010', 'SERV ADUANALES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B011', 'MAQUILA', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'IMPT', 'IMPUESTOS', 'IMPUESTOS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'AGUA', 'SERVICIO DE AGUA', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B016', 'ARRENDAMIENTO EQUIPO', 'SUPPLIEF');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B017', 'ARRENDAMIENTO INMUEBLE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B024', 'ARRENDAMIENTO', NULL);
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'LUZ', 'SERVICIO DE ELECTRICIDAD', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'INTE', 'INTERCOMPAÑIA', 'INTERTRANS');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'NOMI', 'NOMINA', 'NOMINA');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B023', 'RESICO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B004', 'INTANGIBLES', 'SUPPLIERF');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'GVAR', 'GASTOS VARIABLES', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'ADMO', 'ADMO', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'G VI', 'GASTOS DE VIAJE', 'SUPPLIEV');
INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'B022', 'OTROS ARTICULOS', 'SUPPLIEV');
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'GFIO', 'GASTOS FIJO', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C001', 'CUENTA CORRIENTE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C002', 'INTERESES CUENTA CORRIENTE', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'CORI', 'COMISIONES RASSINI INT', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'DESP', 'VALES DE DESPENSA', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'DEVO', 'DEV A CORPOY CHEQUE PROVEEDOR', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'IMMS', 'CUOTAS Y APORTACIONES SOCIALES', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'F AH', 'FONDO DE AHORRO', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'FINI', 'FINIQUITO', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'CORP', 'PAGOS CORPORATIVO', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C009', 'DEUDA BANCOMER', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C010', 'INTERESES BANCOMER', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'CBIB', 'COMISIONES E INTERESES', NULL);
I--NSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C008', 'COMISIÓN AVAL', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C003', 'DEUDA DOCUMENTADA', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C004', 'INTERSES DEUDA DOCUMENTADA', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C005', 'REGALIAS', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'C006', 'STAFF', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'SEPR', 'STAF SEPROSA', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'STAF', 'STAFF MARASA', NULL);
--INSERT INTO equivalences_deal_type (bu, code, des_code, equivalences) VALUES ('0301', 'INFO', 'INFONACOT', NULL);
